find src/ -name "*.c" | xargs cvs annotate src/ &> annotate/FreeBsd_current 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_8_2_0_RELEASE src/ &> annotate/FreeBsd_8_2_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_8_1_0_RELEASE src/ &> annotate/FreeBsd_8_1_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_8_0_0_RELEASE src/ &> annotate/FreeBsd_8_0_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_7_4_0_RELEASE src/ &> annotate/FreeBsd_7_4_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_7_3_0_RELEASE src/ &> annotate/FreeBsd_7_3_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_7_2_0_RELEASE src/ &> annotate/FreeBsd_7_2_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_7_1_0_RELEASE src/ &> annotate/FreeBsd_7_1_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_7_0_0_RELEASE src/ &> annotate/FreeBsd_7_0_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_6_4_0_RELEASE src/ &> annotate/FreeBsd_6_4_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_6_3_0_RELEASE src/ &> annotate/FreeBsd_6_3_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_6_2_0_RELEASE src/ &> annotate/FreeBsd_6_2_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_6_1_0_RELEASE src/ &> annotate/FreeBsd_6_1_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_6_0_0_RELEASE src/ &> annotate/FreeBsd_6_0_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_5_5_0_RELEASE src/ &> annotate/FreeBsd_5_5_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_5_4_0_RELEASE src/ &> annotate/FreeBsd_5_4_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_5_3_0_RELEASE src/ &> annotate/FreeBsd_5_3_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_5_2_1_RELEASE src/ &> annotate/FreeBsd_5_2_1 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_5_2_0_RELEASE src/ &> annotate/FreeBsd_5_2_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_5_1_0_RELEASE src/ &> annotate/FreeBsd_5_1_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_5_0_0_RELEASE src/ &> annotate/FreeBsd_5_0_0 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_4_11_0_RELEASE src/ &> annotate/FreeBsd_4_11_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_4_10_0_RELEASE src/ &> annotate/FreeBsd_4_10_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_4_9_0_RELEASE src/ &> annotate/FreeBsd_4_9_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_4_8_0_RELEASE src/ &> annotate/FreeBsd_4_8_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_4_7_0_RELEASE src/ &> annotate/FreeBsd_4_7_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_4_6_2_RELEASE src/ &> annotate/FreeBsd_4_6_2
find src/ -name "*.c" | xargs cvs annotate -r RELENG_4_6_1_RELEASE src/ &> annotate/FreeBsd_4_6_1
find src/ -name "*.c" | xargs cvs annotate -r RELENG_4_6_0_RELEASE src/ &> annotate/FreeBsd_4_6_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_4_5_0_RELEASE src/ &> annotate/FreeBsd_4_5_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_4_4_0_RELEASE src/ &> annotate/FreeBsd_4_4_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_4_3_0_RELEASE src/ &> annotate/FreeBsd_4_3_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_4_2_0_RELEASE src/ &> annotate/FreeBsd_4_2_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_4_1_1_RELEASE src/ &> annotate/FreeBsd_4_1_1
find src/ -name "*.c" | xargs cvs annotate -r RELENG_4_1_0_RELEASE src/ &> annotate/FreeBsd_4_1_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_4_0_0_RELEASE src/ &> annotate/FreeBsd_4_0_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_3_5_0_RELEASE src/ &> annotate/FreeBsd_3_5_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_3_4_0_RELEASE src/ &> annotate/FreeBsd_3_4_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_3_3_0_RELEASE src/ &> annotate/FreeBsd_3_3_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_3_2_0_RELEASE src/ &> annotate/FreeBsd_3_2_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_3_1_0_RELEASE src/ &> annotate/FreeBsd_3_1_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_3_0_0_RELEASE src/ &> annotate/FreeBsd_3_0_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_2_2_8_RELEASE src/ &> annotate/FreeBsd_2_2_8
find src/ -name "*.c" | xargs cvs annotate -r RELENG_2_2_7_RELEASE src/ &> annotate/FreeBsd_2_2_7
find src/ -name "*.c" | xargs cvs annotate -r RELENG_2_2_6_RELEASE src/ &> annotate/FreeBsd_2_2_6
find src/ -name "*.c" | xargs cvs annotate -r RELENG_2_2_5_RELEASE src/ &> annotate/FreeBsd_2_2_5
find src/ -name "*.c" | xargs cvs annotate -r RELENG_2_2_2_RELEASE src/ &> annotate/FreeBsd_2_2_2
find src/ -name "*.c" | xargs cvs annotate -r RELENG_2_2_1_RELEASE src/ &> annotate/FreeBsd_2_2_1
find src/ -name "*.c" | xargs cvs annotate -r RELENG_2_2_0_RELEASE src/ &> annotate/FreeBsd_2_2_0
find src/ -name "*.c" | xargs cvs annotate -r RELENG_2_1_7_RELEASE src/ &> annotate/FreeBsd_2_1_7
find src/ -name "*.c" | xargs cvs annotate -r RELENG_2_1_6_1_RELEASE src/ &> annotate/FreeBsd_2_1_6_1 
find src/ -name "*.c" | xargs cvs annotate -r RELENG_2_1_6_RELEASE src/ &> annotate/FreeBsd_2_1_6
find src/ -name "*.c" | xargs cvs annotate -r RELENG_2_1_5_RELEASE src/ &> annotate/FreeBsd_2_1_5
find src/ -name "*.c" | xargs cvs annotate -r RELENG_2_1_0_RELEASE src/ &> annotate/FreeBsd_2_1_0
