#!/usr/bin/python
#file_dist.py: file_distribution involved in both porting 

import sys
import os
import csv
import re
import math
import operator

import clone
import config

file_rank_hash = {}
total_port = 0
total_change = 0

FREEBSD_RELEASE_DATES = "../../bsd_data/release_dates/freebsd.csv"
OPENBSD_RELEASE_DATES = "../../bsd_data/release_dates/openbsd.csv"
NETBSD_RELEASE_DATES = "../../bsd_data/release_dates/netbsd.csv"

#=====================================================================#
class fileStat:
	def __init__(self,rev,pcent_1,pcent_2,union,intersect,union_abs,total):
		self.rev = rev
		self.pcent_port1 = pcent_1
		self.pcent_port2 = pcent_2
		self.union = union
		self.intersect = intersect
		self.union_abs = union_abs
		self.total = total
#=====================================================================#

def cal_file_rank(rev,aset,pset1,pset2):

	global file_rank_hash
	global total_port
	global total_change

	file_union = pset1.union(pset2)
	total_port += len(file_union)
	total_change += len(aset)

	for i in file_union:
		diff_line_num = i[0]
		src_file_name = i[1]
		temp_name = src_file_name.split("_")
		src_dir = temp_name[0] + "/" + temp_name[1] + "/" + temp_name[2]
		if (file_rank_hash.has_key(src_dir) == 0):
			file_rank_hash[src_dir] = 0
		file_rank_hash[src_dir] += 1
	
#=====================================================================#
def walk_dir(directory):

	print "directory name = " + directory
	
	for fileName in os.listdir(directory):
		if (config.DEBUG == 1):
			print fileName
		fname = directory + "/" + fileName
		try:
			csvfile = open(fname,"r")
			reader = csv.reader(csvfile,delimiter=',')
			for row in reader:
				diff_line_num = row[0].strip()
				if diff_line_num.startswith("src"):
					pass
				else:
					srcFileName = row[2]
					f, extn = os.path.splitext(fileName)
					year = config.release_dates[f]
					config.src_file_hash[(f,year,diff_line_num)] = srcFileName
					if (config.all_srcFile_by_rev.has_key(year) == 0):
						config.all_srcFile_by_rev[year] = []
					config.all_srcFile_by_rev[year].append((diff_line_num,srcFileName))
	
		
		except IOError as e:
			print fileName + " doesnot exist"
#print config.all_srcFile_by_rev
#=====================================================================#
#=====================================================================#

if (len(sys.argv) < 5):
	 print "Usage: filedist.py input1.txt input2.txt conv_dir output"
	 print "inputN.txt is the output from repertoire"
	 print "conv_dir contains all files that is generated by parsing diff files: usually in the form of conv_dev"
	 print "format: diff_line_no | source_file_line_no| source_file_name"
	 print "output is the output file"
	 sys.exit(2)

in_file1 = sys.argv[1]
in_file2 = sys.argv[2]
dir_name = sys.argv[3]
conv_file = sys.argv[4] 


print "Input Files : " + in_file1 + "," + in_file2
print "Output Files : " + conv_file 

outf = open(conv_file,"w")

config.hash_release_dates(FREEBSD_RELEASE_DATES)
config.hash_release_dates(OPENBSD_RELEASE_DATES)
config.hash_release_dates(NETBSD_RELEASE_DATES)


walk_dir(dir_name)
clone.process_rep_output(in_file1,1)
clone.process_rep_output(in_file2,2)

printLine = "source directory , number of ported edits , % of ported edits in all ported edits\n,";
outf.write(printLine)

if (config.DEBUG > 0):
	print "======= config.all_srcFile_by_rev ==========="
	print config.all_srcFile_by_rev
	print " ===== config.clone_by_rev1 =========="
	print config.clone_by_rev1
	print " ===== config.clone_by_rev2 =========="
	print config.clone_by_rev2


for key in config.clone_by_rev1.iterkeys():
#	print key
	clone_set1 = set()
	clone_set2 = set()
	ported_files = set()
	all_set = set()

	clone_set1 = set(config.clone_by_rev1[key])

	if (config.clone_by_rev2.has_key(key)):
		clone_set2 = set(config.clone_by_rev2[key])
		
	all_set = set(config.all_srcFile_by_rev[key])
	
	cal_file_rank(key,all_set,clone_set1,clone_set2)
	
file_rank = sorted(file_rank_hash.iteritems(),key=operator.itemgetter(1),reverse=True)

if config.DEBUG:
	for key,val in file_rank_hash.iteritems():
		print key + "," + str(val)
		print "================"
	for i in file_rank:
		pcent = (float(i[1]) * 100)/total_port
		print str(i[0]) + "," + str(i[1]) + "," + str(pcent)

	print "total_port = " + str(total_port)
	
outf.write("total_port = " + str(total_port) + "\n")
for i in file_rank:
	pcent = (float(i[1]) * 100)/total_port
	printLine = str(i[0]) + "," + str(i[1]) + "," + str(pcent) + "\n"
	outf.write(printLine)

