cvs diff -cbp -r1.6 -r1.7 src/sys/arch/i386/pci/pciide_machdep.c > diffs/pciide_machdep.c
cvs diff -cbp -r1.27 -r1.28 src/sys/arch/macppc/dev/adb.c > diffs/adb.c
cvs diff -cbp -r1.12 -r1.13 src/sys/arch/macppc/dev/tpms.c > diffs/tpms.c
cvs diff -cbp -r1.11 -r1.12 src/sys/arch/sparc64/sparc64/process_machdep.c > diffs/process_machdep.c
cvs diff -cbp -r1.2 -r1.3 src/sys/compat/aout/compat_aout.c > diffs/compat_aout.c
cvs diff -cbp -r1.4 -r1.5 src/sys/compat/bsdos/bsdos_exec.c > diffs/bsdos_exec.c
cvs diff -cbp -r1.18 -r1.19 src/sys/compat/freebsd/freebsd_exec.c > diffs/freebsd_exec.c
cvs diff -cbp -r1.3 -r1.4 src/sys/compat/hpux/hppa/hpux_exec.c > diffs/hpux_exec.c
cvs diff -cbp -r1.3 -r1.4 src/sys/compat/hpux/m68k/hpux_exec.c > diffs/hpux_exec.c
cvs diff -cbp -r1.18 -r1.19 src/sys/compat/ibcs2/ibcs2_exec.c > diffs/ibcs2_exec.c
cvs diff -cbp -r1.30 -r1.31 src/sys/compat/linux/linux_exec.c > diffs/linux_exec.c
cvs diff -cbp -r1.5 -r1.6 src/sys/compat/osf1/osf1_exec.c > diffs/osf1_exec.c
cvs diff -cbp -r1.18 -r1.19 src/sys/compat/sunos/sunos_exec.c > diffs/sunos_exec.c
cvs diff -cbp -r1.16 -r1.17 src/sys/compat/svr4/svr4_exec.c > diffs/svr4_exec.c
cvs diff -cbp -r1.30 -r1.31 src/sys/compat/ultrix/ultrix_misc.c > diffs/ultrix_misc.c
cvs diff -cbp -r1.3 -r1.4 src/sys/dev/bluetooth/bthidev.c > diffs/bthidev.c
cvs diff -cbp -r1.3 -r1.4 src/sys/dev/bluetooth/btkbd.c > diffs/btkbd.c
cvs diff -cbp -r1.3 -r1.4 src/sys/dev/bluetooth/btms.c > diffs/btms.c
cvs diff -cbp -r1.0 -r1.1 src/sys/dev/bluetooth/btsco.c > diffs/btsco.c
cvs diff -cbp -r1.129 -r1.130 src/sys/dev/i2c/i2c_scan.c > diffs/i2c_scan.c
cvs diff -cbp -r1.30 -r1.31 src/sys/dev/i2c/spdmem.c > diffs/spdmem.c
cvs diff -cbp -r1.28 -r1.29 src/sys/dev/i2c/spdmem.c > diffs/spdmem.c
cvs diff -cbp -r1.101 -r1.102 src/sys/dev/ic/wdc.c > diffs/wdc.c
cvs diff -cbp -r1.63 -r1.64 src/sys/dev/pci/azalia.c > diffs/azalia.c
cvs diff -cbp -r1.291 -r1.292 src/sys/dev/pci/pciide.c > diffs/pciide.c
cvs diff -cbp -r1.4 -r1.5 src/sys/dev/sbus/if_gem_sbus.c > diffs/if_gem_sbus.c
cvs diff -cbp -r1.15 -r1.16 src/sys/dev/sbus/magma.c > diffs/magma.c
cvs diff -cbp -r1.15 -r1.16 src/sys/dev/sbus/stp4020.c > diffs/stp4020.c
cvs diff -cbp -r1.96 -r1.97 src/sys/dev/usb/ehci.c > diffs/ehci.c
cvs diff -cbp -r1.13 -r1.14 src/sys/dev/usb/ubt.c > diffs/ubt.c
cvs diff -cbp -r1.67 -r1.68 src/sys/kern/exec_elf.c > diffs/exec_elf.c
cvs diff -cbp -r1.157 -r1.158 src/sys/kern/init_main.c > diffs/init_main.c
cvs diff -cbp -r1.108 -r1.109 src/sys/kern/kern_exec.c > diffs/kern_exec.c
cvs diff -cbp -r1.102 -r1.103 src/sys/kern/kern_sig.c > diffs/kern_sig.c
cvs diff -cbp -r1.78 -r1.79 src/sys/kern/tty.c > diffs/tty.c
cvs diff -cbp -r1.60 -r1.61 src/sys/kern/vfs_vnops.c > diffs/vfs_vnops.c
cvs diff -cbp -r1.34 -r1.35 src/sys/uvm/uvm_unix.c > diffs/uvm_unix.c
cvs diff -cbp -r1.39 -r1.40 src/usr.bin/make/cond.c > diffs/cond.c
cvs diff -cbp -r1.12 -r1.13 src/lib/csu/common_elf/crtbegin.c > diffs/crtbegin.c
cvs diff -cbp -r1.9 -r1.10 src/lib/csu/common_elf/crtbeginS.c > diffs/crtbeginS.c
cvs diff -cbp -r1.6 -r1.7 src/lib/csu/common_elf/crtend.c > diffs/crtend.c
cvs diff -cbp -r1.5 -r1.6 src/lib/csu/common_elf/crtendS.c > diffs/crtendS.c
cvs diff -cbp -r1.13 -r1.14 src/lib/libc/rpc/xdr_mem.c > diffs/xdr_mem.c
cvs diff -cbp -r1.12 -r1.13 src/lib/libc/rpc/xdr_rec.c > diffs/xdr_rec.c
cvs diff -cbp -r1.11 -r1.12 src/lib/libc/rpc/xdr_stdio.c > diffs/xdr_stdio.c
cvs diff -cbp -r1.0 -r1.1 src/sys/arch/arm/s3c2xx0/s3c2410.c > diffs/s3c2410.c
cvs diff -cbp -r1.0 -r1.1 src/sys/arch/arm/s3c2xx0/s3c2410_intr.c > diffs/s3c2410_intr.c
cvs diff -cbp -r1.0 -r1.1 src/sys/arch/arm/s3c2xx0/s3c24x0_clk.c > diffs/s3c24x0_clk.c
cvs diff -cbp -r1.0 -r1.1 src/sys/arch/arm/s3c2xx0/s3c2xx0_busdma.c > diffs/s3c2xx0_busdma.c
cvs diff -cbp -r1.0 -r1.1 src/sys/arch/arm/s3c2xx0/s3c2xx0_intr.c > diffs/s3c2xx0_intr.c
cvs diff -cbp -r1.0 -r1.1 src/sys/arch/arm/s3c2xx0/s3c2xx0_mutex.c > diffs/s3c2xx0_mutex.c
cvs diff -cbp -r1.0 -r1.1 src/sys/arch/arm/s3c2xx0/s3c2xx0_space.c > diffs/s3c2xx0_space.c
cvs diff -cbp -r1.0 -r1.1 src/sys/arch/arm/s3c2xx0/sscom.c > diffs/sscom.c
cvs diff -cbp -r1.0 -r1.1 src/sys/arch/arm/s3c2xx0/sscom_s3c2410.c > diffs/sscom_s3c2410.c
cvs diff -cbp -r1.6 -r1.7 src/sys/arch/sgi/dev/gbe.c > diffs/gbe.c
cvs diff -cbp -r1.31 -r1.32 src/sys/arch/sparc/dev/amd7930.c > diffs/amd7930.c
cvs diff -cbp -r1.63 -r1.64 src/sys/arch/sparc/dev/fd.c > diffs/fd.c
cvs diff -cbp -r1.20 -r1.21 src/sys/arch/sparc/dev/magma.c > diffs/magma.c
cvs diff -cbp -r1.19 -r1.20 src/sys/arch/sparc/dev/magma.c > diffs/magma.c
cvs diff -cbp -r1.20 -r1.21 src/sys/arch/sparc/dev/spif.c > diffs/spif.c
cvs diff -cbp -r1.18 -r1.19 src/sys/arch/sparc/dev/ts102.c > diffs/ts102.c
cvs diff -cbp -r1.46 -r1.47 src/sys/arch/sparc/dev/zs.c > diffs/zs.c
cvs diff -cbp -r1.31 -r1.32 src/sys/arch/sparc/sparc/intr.c > diffs/intr.c
cvs diff -cbp -r1.151 -r1.152 src/sys/arch/sparc/sparc/pmap.c > diffs/pmap.c
cvs diff -cbp -r1.12 -r1.13 src/sys/arch/sparc/sparc/process_machdep.c > diffs/process_machdep.c
cvs diff -cbp -r1.4 -r1.5 src/sys/netbt/bt_proto.c > diffs/bt_proto.c
cvs diff -cbp -r1.7 -r1.8 src/sys/netbt/hci_event.c > diffs/hci_event.c
cvs diff -cbp -r1.8 -r1.9 src/sys/netbt/hci_link.c > diffs/hci_link.c
cvs diff -cbp -r1.6 -r1.7 src/sys/netbt/hci_socket.c > diffs/hci_socket.c
cvs diff -cbp -r1.8 -r1.9 src/sys/netbt/hci_unit.c > diffs/hci_unit.c
cvs diff -cbp -r1.2 -r1.3 src/sys/netbt/l2cap_lower.c > diffs/l2cap_lower.c
cvs diff -cbp -r1.5 -r1.6 src/sys/netbt/l2cap_misc.c > diffs/l2cap_misc.c
cvs diff -cbp -r1.2 -r1.3 src/sys/netbt/l2cap_socket.c > diffs/l2cap_socket.c
cvs diff -cbp -r1.2 -r1.3 src/sys/netbt/l2cap_upper.c > diffs/l2cap_upper.c
cvs diff -cbp -r1.3 -r1.4 src/sys/netbt/rfcomm_dlc.c > diffs/rfcomm_dlc.c
cvs diff -cbp -r1.4 -r1.5 src/sys/netbt/rfcomm_session.c > diffs/rfcomm_session.c
cvs diff -cbp -r1.3 -r1.4 src/sys/netbt/rfcomm_socket.c > diffs/rfcomm_socket.c
cvs diff -cbp -r1.5 -r1.6 src/sys/netbt/rfcomm_upper.c > diffs/rfcomm_upper.c
cvs diff -cbp -r1.2 -r1.3 src/sys/netbt/sco_socket.c > diffs/sco_socket.c
cvs diff -cbp -r1.2 -r1.3 src/sys/netbt/sco_upper.c > diffs/sco_upper.c
cvs diff -cbp -r1.191 -r1.192 src/sys/netinet/ip_output.c > diffs/ip_output.c
cvs diff -cbp -r1.103 -r1.104 src/sys/netinet6/icmp6.c > diffs/icmp6.c
cvs diff -cbp -r1.56 -r1.57 src/sys/nfs/nfs_bio.c > diffs/nfs_bio.c
cvs diff -cbp -r1.55 -r1.56 src/sys/nfs/nfs_bio.c > diffs/nfs_bio.c
cvs diff -cbp -r1.14 -r1.15 src/sys/nfs/nfs_kq.c > diffs/nfs_kq.c
cvs diff -cbp -r1.91 -r1.92 src/sys/nfs/nfs_subs.c > diffs/nfs_subs.c
cvs diff -cbp -r1.109 -r1.110 src/sys/nfs/nfs_vnops.c > diffs/nfs_vnops.c
cvs diff -cbp -r1.108 -r1.109 src/sys/nfs/nfs_vnops.c > diffs/nfs_vnops.c
cvs diff -cbp -r1.107 -r1.108 src/sys/nfs/nfs_vnops.c > diffs/nfs_vnops.c
cvs diff -cbp -r1.106 -r1.107 src/sys/nfs/nfs_vnops.c > diffs/nfs_vnops.c
