#!/usr/bin/python
#filter.py:  

import sys
import os
import csv
import re
import clone
import sets
import math
#=====================================================================#

DEBUG = 0

gt_set = set()
repertoire_set = set()

#=====================================================================#

def process_ground_truth(log_file):
	global gt_set

	#print annotate_hash
	chf = open(log_file,"r")
	ch_reader = csv.reader(chf, delimiter=',')

	for row in ch_reader:
		fname = row[0]
		fname = fname.strip("'")
		diff_no = int(row[1])
		gt_set.add((fname,diff_no))	
		

	chf.close()
#	print gt_hash

#=====================================================================#
def process_repertoire_log(rp_file):

	global repertoire_set

	rpf = open(rp_file,"r")

	rp_reader = csv.reader(rpf, delimiter=',')

	for row in rp_reader:
		fname = row[0]
		if fname.startswith("====="):
			pass
		else:
			fname = fname.partition(".csv")[0] + ".c"
			fname = fname.strip()
			version = str(row[1].strip())
			change_line = row[6]
			add = change_line.partition(":")[2]
			cl = change_line.partition(":")[0]
			cl = cl.partition(".")[2]
			start_line, end_line = cl.split('-')
			
#		print fname + "," + version + "," + change_line + "," + add
#		print fname + "," + version + "," + change_line + "," + start_line + "," + end_line

			start = int(start_line)
			end = int(end_line) + 1
		
			key = fname
			
			for i in range(start,end):
				repertoire_set.add((key,i))
			
	rpf.close()

#=====================================================================#
def walk_dir(directory):
	
	for f in os.listdir(directory):
		print f
		fname = directory + "/" + f
		process_repertoire_log(fname)
#=====================================================================#

if (len(sys.argv) < 3):
	 print "Usage: prec_recall.py ground_truth.csv repertoire"
	 print "ground_truth.csv is our ground truth"
	 print "this is generated by create_groundthruth.py"
	 print "repertoire contains all repertoire output"
	 sys.exit()

gt_file = sys.argv[1]
rp_file = sys.argv[2]

print "Input : " + gt_file + "," + rp_file

process_ground_truth(gt_file)
process_repertoire_log(rp_file)

#for i in gt_set:
#	print i

#print "============="
#for i in repertoire_set:
#	print i
#sys.exit()

#-----------Precision & Recall Calculation -------------#
E = gt_set
M = repertoire_set

I = M.intersection(E)

print "len E =" + str(len(E)) 
print "len M =" + str(len(M)) 
print "len I =" + str(len(I)) 


prec = float(len(I)) / len(M)
recall = float(len(I)) / len(E)
print "precision = " + str(prec)
print "recall = " + str(recall)

out_file = open("boo.csv", 'a')
printLine = rp_file + "," + str(prec) + "," + str(recall) + "\n"
out_file.writelines(printLine)
out_file.close()
